routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware'=>'auth'],function()
{
	Route::get('logout','Auth\LoginController@logout')->name('logout');
    Route::get('users/logout','Auth\LoginController@userLogout')->name('users.logout');

});


Auth::routes();
	
	


Route::prefix('admin')->group(function(){

 Route::get('/login','Auth\AdminLogingController@showLoginForm')->name('admin.login');
 Route::post('/login','Auth\AdminLogingController@login')->name('admin.login.submit');
 Route::get('/', 'Admin\AdminController@index')->name('admin.dashboard');
 Route::get('/logout', 'Auth\AdminLogingController@logout')->name('admin.logout');

 	

});

Route::group([
		'as' => 'admin',
		'prefix' => 'admin',
		'namespace' => 'Admin'
	], function(){
		Route::resource('students','StudentController');
		Route::resource('teachers','TeacherController');
		Route::resource('modules','ModuleController');

			});

Route::group([
		'as' => 'teacher',
		'prefix' => 'teacher',
		'namespace' => 'Teacher'
	], function(){
		Route::get('index', [
			'as' =>'index',
			'uses' => 'HomeController@index'
			]);
		
		Route::resource('students','StudentController');
		Route::resource('modules','ModuleController');
	});

Route::get('/user/redirect', [
		'as'   => 'user.redirect',
		function(){

			switch (Auth::user()->who) {
				case 'teacher':
					return Redirect::route('teachers.index');
					break;

				case 'student':
					return Redirect::route('students.index');
					break;
				
				default:
					return App::abort(400);
					break;
			}
		}
		]);

app/Module.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Teacher;

class Module extends Model
{
	protected $fillable = ['entitled_module'];
	
    public function teachers(){

    	return $this->belongsToMany(Teacher::class,'module_teacher','module_id','teacher_id');
    }
}

app/Http/Controllers/Admin/ModuleController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Module;
use Session;

class ModuleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //All modules
        
        $modules = Module::all();
        return view('Admin.modules.index')->withModules($modules);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //Redirect to the Create view
        return view('Admin.modules.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Validate input
        $this->validate($request,[

                'module_name' => 'required|unique:modules,entitled_module'

            ]);
        $module = new Module;
        $module->entitled_module = $request->module_name;
        $module->save();
        Session::flash('success','Le module a été ajouté avec succés');
        //redirect back to index
         return redirect()->route('modules.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //Get the module by id 

        $module = Module::find($id);
        return view('Admin.modules.edit')->withModule($module);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //Validate input
        $this->validate($request,[

                'mname' => 'required|unique:modules,entitled_module'

            ]);
     
        $inputData = $request->all();

        $module = Module::find($id);
        $module->update($inputData);

         return redirect()->route('modules.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Admin/modules/create.blade.php
@extends('main')

@section('content')


<div class="row">
	    <div class="col-md-6 col-md-offset-3">
	        <div class="panel panel-default">
	            <div class="panel-heading">
	                <h4>Creation d'un Module</h4>
	            </div>
	            <div class="panel-body">
	           <form action="{{route('modules.store')}}" method="POST">
	           {{csrf_field()}}  
	           	

	           	<div class="form-group">
	                    <label for="name">Nom du Module :</label>
	                    <input class="form-control" name="module_name" placeholder="Nom du Module" type="text" />
	                   
	                </div>

	                <div class="form-group">
	                    <input name="submit" type="submit" class="btn btn-primary" value="Inserer" />
	                    <input name="cancel" type="reset" class="btn btn-default" value="Cancel" />
	                </div>
	           </form>
	           
	            </div>
	        </div>
	    </div>
	</div>
@endsection

resources/views/Admin/modules/edit.blade.php
@extends('main')

@section('content')



<div class="row">
	    <div class="col-md-6 col-md-offset-3">
	        <div class="panel panel-default">
	            <div class="panel-heading">
	                <h4>Modification du nom du module</h4>
	            </div>
	            <div class="panel-body">
	               
	                  <form action="{{route('modules.update',$module->id)}}" method="POST">
		{{csrf_field()}}  
	    {{method_field('PUT')}}

	                <div class="form-group">
	                    <label for="name">Nom du Module :</label>
	                    <input class="form-control" name="mname" placeholder="Nom du Module" type="text" value="{{ $module->entitled_module }}" /> 
	                   
	                </div>
	                
	                <div class="form-group">
	                    <input name="submit" type="submit" class="btn btn-primary" value="Update" />
	                    <input name="cancel" type="reset" class="btn btn-default" value="Cancel" />
	                </div>
	           
	                </form>
	            </div>
	        </div>
	    </div>
	</div>

@endsection

resources/views/Admin/modules/index.blade.php
@extends('main')

@section('content')

<div class="row">
		<div class="col-md-6 col-md-offset-3">

					<h3>Liste des Modules</h3>
			<center>
			<table class="table table-striped">
		    	<thead>
		    		<tr>
		        		<th>ID</th>
		        		<th>Module</th>
		        		<th class="ico">Modifier/Supprimer</th>
		      		</tr>
		    	</thead>
		    	<tbody>
					 
						@foreach ($modules as $module)
						
							<tr>
						        <td> {{ $module->id }} </td>
						        <td>  {{ $module->entitled_module }} </td>
						        <td class="ico">
					        		
							        <button type="button" class="btn btn-default btn-sm">
							        	<a href="{{route('modules.edit', $module->id)}}">
									    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
									</button>
									<button type="button" class="btn btn-default btn-sm">
							        	<a href="#">
									    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
									</button>
									
								</td>
						   </tr>
					@endforeach
					
				</tbody>
	  		</table>
 
		
	</div>
	
</div>

@endsection