routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware'=>'auth'],function()
{
	Route::get('logout','Auth\LoginController@logout')->name('logout');
    Route::get('users/logout','Auth\LoginController@userLogout')->name('users.logout');

});


Auth::routes();
	
	


Route::prefix('admin')->group(function(){

 Route::get('/login','Auth\AdminLogingController@showLoginForm')->name('admin.login');
 Route::post('/login','Auth\AdminLogingController@login')->name('admin.login.submit');
 Route::get('/', 'Admin\AdminController@index')->name('admin.dashboard');
 Route::get('/logout', 'Auth\AdminLogingController@logout')->name('admin.logout');

 	

});

Route::group([
		'as' => 'admin',
		'prefix' => 'admin',
		'namespace' => 'Admin'
	], function(){
		Route::resource('students','StudentController');
		Route::resource('teachers','TeacherController');
		Route::resource('modules','ModuleController');

			});

Route::group([
		'as' => 'teacher',
		'prefix' => 'teacher',
		'namespace' => 'Teacher'
	], function(){
		Route::get('index', [
			'as' =>'index',
			'uses' => 'HomeController@index'
			]);
		
		Route::resource('students','StudentController');
		Route::resource('modules','ModuleController');
	});

Route::get('/user/redirect', [
		'as'   => 'user.redirect',
		function(){

			switch (Auth::user()->who) {
				case 'teacher':
					return Redirect::route('teachers.index');
					break;

				case 'student':
					return Redirect::route('students.index');
					break;
				
				default:
					return App::abort(400);
					break;
			}
		}
		]);

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable=['CNE','fname','lname','adress','city','image','email','phone_number'];
}

app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Module;

class Teacher extends Model
{
    protected $fillable=['fname','lname','adress','city','image','email','phone'];
    
    public function modules(){

    	return $this->belongsToMany(Module::class);
    }
}

app/Http/Controllers/Admin/StudentController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Student;
use Session;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = Student::all();
        return view('Admin.students.allStudents')->withStudents($students);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Admin.students.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validate input
        $this->validate($request,[

            'CNE'=>'required',
            'fname'=>'required|max:20',
            'lname'=>'required',
            'adress' => 'required',
            'city'=>'required|max:10',  
            'image' => 'required',
            'email'=>'required' ,   
            'phone'=>'required',
            'birth_date'=>'required|date',
            'birth_city'=>'required'

            ]);

        //Save the student as user 
         $user = new User;
         $user->who = "student";
         $user->name = $request->fname;
         $user->email = $request->email;
         $user->password = Hash::make('secret');
         $user->save();

        $student = new Student($request->input());
        $student->CNE = $request->CNE;
        $student->fname = $request->fname;
        $student->lname = $request->lname;
        $student->adress = $request->adress;
        $student->city = $request->city;
        $student->email = $request->email;
        $student->phone = $request->phone;
        $student->birth_date = $request->birth_date;
        $student->birth_city = $request->birth_city;
        if($file = $request->hasFile('image')){

            $file = $request->file('image');
            $fileName = getClientOriginalName();
            $destinationPath = public_path().'/images/'; 
            $file->move($destinationPath,$fileName);
            $student->image = $fileName;


         }
         $student->save();
         Session::flash('success','The student is successfully saved!!');
         return redirect()->route('students.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Admin/TeacherController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\file;
use Illuminate\Support\Facades\Input;
use App\Teacher;
use App\Module;
use App\User;
use Session;
use Hash;


class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //All teachers
        $teachers = Teacher::all();
        return view('Admin.teachers.AllTeachers')->withTeachers($teachers);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $modules = Module::all();
        return view('Admin.teachers.create')->withModules($modules);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
         $this->validate($request,[

            'fname'=>'required|max:20',
            'lname'=>'required',
            'adress' => 'required',
            'city'=>'required|max:10',  
            'image' => 'required',
            'email'=>'required' ,   
            'phone'=>'required'   
        ]);

         //Save the teacher as user 
         $user = new User;
         $user->who = "teacher";
         $user->name = $request->fname;
         $user->email = $request->email;
         $user->password = Hash::make('secret');
         $user->save();

         //Save the teacher 

         $teacher = new Teacher($request->input());
         $teacher->fname = $request->fname;
         $teacher->lname = $request->lname;
         $teacher->adress = $request->adress;
         $teacher->city = $request->city;
         $teacher->email = $request->email;
         $teacher->phone = $request->phone;
         if($file = $request->hasFile('image')){
            $file = $request->file('image');
            $fileName = getClientOriginalName();
            $destinationPath = public_path().'/images/'; 
            $file->move($destinationPath,$fileName);
            $teacher->image = $fileName;


         }
        
         $teacher->save();
         $teacher->modules()->sync($request->modules, false);
         
       //   Session::flash('success','The teacher is successfully saved!!');
         return redirect()->route('teachers.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
             */
    public function show($id)
    {
        //find teacher
        $teacher = Teacher::find($id);
        return view('Admin.teachers.show',compact('teacher'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //get teacher by id
        $teacher = Teacher::find($id);
        $modules = Module::all();
        return view('Admin.teachers.edit')->with('teacher',$teacher)->withModules($modules);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       
          $this->validate($request,[

            'fname'=>'required|max:20',
            'lname'=>'required',
            'adress' => 'required',
            'city'=>'required|max:10',  
            'image' => 'required',
            'email'=>'required' ,   
            'phone'=>'required'   
        ]);

          $inputData = $request->all();
           //find the teacher updated by id
        $teacher = Teacher::find($id);
        $teacher->update($inputData);
        if (isset($request->modules)) {

            $teacher->modules()->sync($request->modules);
        }else{
            $teacher->modules()->sync(array());
        }

        return redirect()->route('teachers.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //find the teacher by id then delete him
        $teacher = Teacher::find($id);
        $teacher->delete();
        return redirect()->route('teachers.index');
    }
}

app/Http/Controllers/Teacher/HomeController.php
<?php

namespace App\Http\Controllers\Teacher;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Teacher.home');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Teacher/students/allStudents.blade.php
@extends('main')

@section('content')


<div class="row">
	
		<div class="col-md-6 col-md-offset-2">

			<h3>Liste des etudiants</h3>
			<table class="table table-striped">
		    	<thead>
		    		<tr>
		        		<th>Photo</th>
		        		<th>CNE</th>
		        		<th>Nom</th>
		        		<th>Prenom</th>
		        		<th>Date naissance</th>
		        		<th>ville naissance</th>
		        		<th>Adresse</th>
		        		<th>Ville</th>
		        		<th>Email</th>
		        		<th>Telephone</th>
		        		<th class="ico">Affecter un cours</th>
		        		<th class="ico">View</th>
		        		<th class="ico">Edit/Del</th>
		      		</tr>
		    	</thead>
		    	<tbody>
					@foreach($students as $student)
							<tr>
								<td> image </td>
						        <td>{{$student->CNE}}</td>
						        <td>{{$student->fname}}</td>
						        <td>{{$student->lname}}</td>
						        <td>{{$student->birth_date}}</td>
						        <td> {{$student->birth_city}}</td>
						        <td>{{$student->adress}}</td>
						        <td>{{$student->city}}</td>
						        <td>{{$student->email}}</td>
						        <td>{{$student->phone}}</td>
						       <td class="ico"> <button type="button" class="btn btn-default btn-sm">
							        	<a href="#">
									    <span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>
									</button></td>
						 <td class="ico">
					        	
							        <button type="button" class="btn btn-default btn-sm">
							        	<a href="#">
									    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
									</button>
									
							</td>
						        
									
								</td>
						        <td class="ico">
					        		
							        <button type="button" class="btn btn-default btn-sm">
							        	<a href="#">
									    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
									</button>
									<button type="button" class="btn btn-default btn-sm">
							        	<a href="#">
									    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
									</button>
									
							</tr>
					@endforeach
					
				</tbody>
	  		</table>
			<br>
			<center>
	  			
	  			
				<button type="button" class="btn btn-default btn"/>
		        	<a href="#">
				    <span class="glyphicon glyphicon-export" aria-hidden="true"></span>
				    Export as XLS</a>
				</button>
			</center>	
			<br><br>
@endsection

resources/views/Teacher/students/create.blade.php
@extends('main')

@section('content')
 
 <div class="row">
      <div class="col-md-6 col-md-offset-3">
	        <div class="panel panel-default">
              <div class="panel-heading">
	                <h4>Creation d'un compte etudiant</h4>
	            </div>
	            <div class="panel-body">
	                <form action="{{route('students.store')}}" method="post">
	                {{csrf_field()}} 

	               
	              

	                <div class="form-group">
	                    <label for="CNE">CNE :</label>
	                    <input class="form-control" name="CNE" placeholder="CNE" type="text"  />
	                   
	                </div>
					
					<div class="form-group">
	                    <label for="fname">Prenom :</label>
	                    <input class="form-control" name="fname" placeholder="Prenom" type="text" />
	                   
	                </div>

	                <div class="form-group">
	                    <label for="lname">Nom :</label>
	                    <input class="form-control" name="lname" placeholder="Nom" type="text" />
	                    
	                </div>

	                <div class="form-group">
	                    <label for="birth_date">Date de Naissance :</label>
	                    <input class="form-control" name="birth_date" placeholder="Date Naissance" type="date" />
	                    
	                </div>

	                <div class="form-group">
	                    <label for="birth_city">Ville de Naissance :</label>
	                    <input class="form-control" name="birth_city" placeholder="Ville Naissance" type="text" />
	                    
	                </div>

	                <div class="form-group">
	                    <label for="adress">Adresse :</label>
	                    <input class="form-control" name="adress" placeholder="Adresse" type="text"  />
	                    
	                </div>

	                <div class="form-group">
	                    <label for="city">Ville :</label>
	                    <input class="form-control" name="city" placeholder="Ville" type="text" />
	                    
	                </div>

	                 <div class="form-group">
		                <div class="row">
		                    <div class="col-md-12">
		                        <label for="photo" class="control-label">Photo</label>
		                    </div>
		                </div>
		            </div>

		            <div class="form-group">
		                <div class="row">
		                    <div class="col-md-12">
		                    	<input type="file" name="image" id="image" class="form-control">
		                    </div>
		                </div>
		            </div>
	                
	                <div class="form-group">
	                    <label for="email">Email :</label>
	                    <input class="form-control" name="email" placeholder="Email" type="text"  />
	                    
	                </div>

	                <div class="form-group">
	                    <label for="phone">Telephone :</label>
	                    <input class="form-control" name="phone" placeholder="Telephone" type="text"  />
	                   
	                </div>

	                <div class="form-group">
	                    <input name="submit" type="submit" class="btn btn-primary" value="Inserer" />
	                    <input name="cancel" type="reset" class="btn btn-default" value="Cancel" />
	                </div>
	                
	            </form>
	            </div>
	        </div>
	        </div>
	        </div>
@endsection

resources/views/Teacher/students/show.blade.php
{{-- @extends('main')

@section('content')


	<div class="container">
	
		

	<center>
		
		
		<h3>L'étudiant <b>{{$student->fname}}  {{$student->lname}}</b></h3>
		<div class="col-md-6 col-md-offset-3 well">
			<img src="#" height="250" width="250" class="pull-left" alt="Pas d'image">
			<p>CNE : <b>{{$student->CNE}}</b></p>
			<p>Nom : <b>{{$student->lname}}</b></p>
			<p>Prenom : <b>{{$student->fname}}</b></p>
			<p>Date de naissance : <b>{{$student->birth_date}}</b></p>
			<p>Ville de naissance : <b>{{$student->birth_city}}</b></p>
			<p>Adresse : <b>{{$student->adress}}</b></p>
			<p>Ville : <b>{{$student->city}}</b></p>
			<p>Email : <b>{{$student->email}}</b></p>
			<p>Telephone : <b>{{$student->phone}}</b></p>
		</div>

		<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

		<!-- Si il n'y a pas d'absence id_absence va etre vide ;) donc je l'exploit-->		
		

			<h3>Table d'absence de l'étudiant <b>{{$student->lname}} {{$student->fname}}</b></h3>
			<br>           
			<table class="table table-striped">
		    	<thead>
		    		<tr>
		        		<th>Module</th>
		        		<th>Date seance</th>
		        		<th>Heure debut</th>
		        		<th>Heure fin</th>
		        		<th>Type seance</th>
		        		<th>Justifiee</th>
		        		<th>Commentaire</th>
		      		</tr>
		    	</thead>
		    	<tbody>
					
					
						@foreach ($etuAbsInfo->result() as $row)
						{
							echo "<tr>";
						        echo "<td>" . $row->intitule_module . "</td>";
						        echo "<td>" . $row->date_seance . "</td>";
						        echo "<td>" . $row->heure_debut . "</td>";
						        echo "<td>" . $row->heure_fin . "</td>";
						        echo "<td>" . $row->type_seance . "</td>";
						        echo "<td>" . $row->justifiee . "</td>";
						        echo "<td>" . $row->comm_abs . "</td>";
						    echo "</tr>";
						}
					?>
				</tbody>
	  		</table>

@endsection --}}