routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware'=>'auth'],function()
{
	Route::get('logout','Auth\LoginController@logout')->name('logout');
    Route::get('users/logout','Auth\LoginController@userLogout')->name('users.logout');

});


Auth::routes();
	
	


Route::prefix('admin')->group(function(){

 Route::get('/login','Auth\AdminLogingController@showLoginForm')->name('admin.login');
 Route::post('/login','Auth\AdminLogingController@login')->name('admin.login.submit');
 Route::get('/', 'Admin\AdminController@index')->name('admin.dashboard');
 Route::get('/logout', 'Auth\AdminLogingController@logout')->name('admin.logout');

 	

});

Route::group([
		'as' => 'admin',
		'prefix' => 'admin',
		'namespace' => 'Admin'
	], function(){
		Route::resource('students','StudentController');
		Route::resource('teachers','TeacherController');
		Route::resource('modules','ModuleController');

			});

Route::group([
		'as' => 'teacher',
		'prefix' => 'teacher',
		'namespace' => 'Teacher'
	], function(){
		Route::get('index', [
			'as' =>'index',
			'uses' => 'HomeController@index'
			]);
		
		Route::resource('students','StudentController');
		Route::resource('modules','ModuleController');
	});

Route::get('/user/redirect', [
		'as'   => 'user.redirect',
		function(){

			switch (Auth::user()->who) {
				case 'teacher':
					return Redirect::route('teachers.index');
					break;

				case 'student':
					return Redirect::route('students.index');
					break;
				
				default:
					return App::abort(400);
					break;
			}
		}
		]);

app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Module;

class Teacher extends Model
{
    protected $fillable=['fname','lname','adress','city','image','email','phone'];
    
    public function modules(){

    	return $this->belongsToMany(Module::class);
    }
}

app/Http/Controllers/Admin/TeacherController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\file;
use Illuminate\Support\Facades\Input;
use App\Teacher;
use App\Module;
use App\User;
use Session;
use Hash;


class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //All teachers
        $teachers = Teacher::all();
        return view('Admin.teachers.AllTeachers')->withTeachers($teachers);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $modules = Module::all();
        return view('Admin.teachers.create')->withModules($modules);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
         $this->validate($request,[

            'fname'=>'required|max:20',
            'lname'=>'required',
            'adress' => 'required',
            'city'=>'required|max:10',  
            'image' => 'required',
            'email'=>'required' ,   
            'phone'=>'required'   
        ]);

         //Save the teacher as user 
         $user = new User;
         $user->who = "teacher";
         $user->name = $request->fname;
         $user->email = $request->email;
         $user->password = Hash::make('secret');
         $user->save();

         //Save the teacher 

         $teacher = new Teacher($request->input());
         $teacher->fname = $request->fname;
         $teacher->lname = $request->lname;
         $teacher->adress = $request->adress;
         $teacher->city = $request->city;
         $teacher->email = $request->email;
         $teacher->phone = $request->phone;
         if($file = $request->hasFile('image')){
            $file = $request->file('image');
            $fileName = getClientOriginalName();
            $destinationPath = public_path().'/images/'; 
            $file->move($destinationPath,$fileName);
            $teacher->image = $fileName;


         }
        
         $teacher->save();
         $teacher->modules()->sync($request->modules, false);
         
       //   Session::flash('success','The teacher is successfully saved!!');
         return redirect()->route('teachers.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
             */
    public function show($id)
    {
        //find teacher
        $teacher = Teacher::find($id);
        return view('Admin.teachers.show',compact('teacher'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //get teacher by id
        $teacher = Teacher::find($id);
        $modules = Module::all();
        return view('Admin.teachers.edit')->with('teacher',$teacher)->withModules($modules);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       
          $this->validate($request,[

            'fname'=>'required|max:20',
            'lname'=>'required',
            'adress' => 'required',
            'city'=>'required|max:10',  
            'image' => 'required',
            'email'=>'required' ,   
            'phone'=>'required'   
        ]);

          $inputData = $request->all();
           //find the teacher updated by id
        $teacher = Teacher::find($id);
        $teacher->update($inputData);
        if (isset($request->modules)) {

            $teacher->modules()->sync($request->modules);
        }else{
            $teacher->modules()->sync(array());
        }

        return redirect()->route('teachers.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //find the teacher by id then delete him
        $teacher = Teacher::find($id);
        $teacher->delete();
        return redirect()->route('teachers.index');
    }
}

app/Http/Controllers/Teacher/HomeController.php
<?php

namespace App\Http\Controllers\Teacher;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Teacher.home');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Admin/teachers/AllTeachers.blade.php
@extends('main')

@section('content')

  <div class="row">
      <div class="col-md-6 col-md-offset-3">
		<h3>Liste des enseignants</h3>
			<table class="table table-striped table-inverse">
		    	<thead>
		    		<tr>
		        		<th>Photo</th>
		        		<th>Nom</th>
		        		<th>Prenom</th>
		        		<th>Adresse</th>
		        		<th>Ville</th>
		        		<th>Email</th>
		        		<th>Telephone</th>
		        		<th class="ico">Affecter à un cours</th>
		        	
		        		<th class="ico">Consulter</th>
		        		<th class="ico">Modifier/Supprimer</th>
		      		</tr>
		    	</thead>
		    	<tbody>
					
						@foreach ($teachers as $teacher)
						<tr>
						<td>image</td>
						<td>{{$teacher->fname}}</td>
						<td>{{$teacher->lname}}</td>
						<td>{{$teacher->adress}}</td>
						<td>{{$teacher->city}}</td>
						<td>{{$teacher->email}}</td>
						<td>{{$teacher->phone}}</td>
						<td class="ico"> <button type="button" class="btn btn-default btn-sm">
							        	<a href="#">
									    <span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>
									</button></td>
										<td class="ico"> <button type="button" class="btn btn-default btn-sm">
							        	<a href="{{route('teachers.show',$teacher->id)}}">
									    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
									</button></td>
						 
						        
						        <td class="ico">
					        		
							        <button type="button" class="btn btn-default btn-sm">
							        	<a href="{{route('teachers.edit',$teacher->id)}}"/>
									    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
									    </a>
									</button>

									<form action="{{route('teachers.destroy',$teacher->id)}}" method="POST">
									{{csrf_field()}}
                            {{method_field('DELETE')}}

										<button type="submit" class="btn btn-default btn-sm">
							        	
									    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
									    
									</button>
									</form>
										
									
								</td>	
									
							</tr>
					@endforeach
					
				</tbody>
	  		</table>
			<br>
			<center>
	  			
	  			
				<button type="button" class="btn btn-default btn"/>
		        	<a href="#">
				    <span class="glyphicon glyphicon-export" aria-hidden="true"></span>
				    Export as XLS</a>
				</button>
			</center>	
			<br><br>
		</div>
		</div>

@endsection

resources/views/Admin/teachers/create.blade.php
@extends('main')

@section('stylesheet')
{!! Html::style('css/select2.min.css') !!}


@section('content')


 <div class="row">
      <div class="col-md-6 col-md-offset-3">
	        <div class="panel panel-default">
	            <div class="panel-heading">
	                <h4>Creation d'un compte enseignant</h4>
	            </div>
	            <div class="panel-body">
	           
	              <form action="{{route('teachers.store')}}" method="POST">
		{{csrf_field()}}  
	              
	           

	              
					
					<div class="form-group">
	                    <label for="name">Prenom :</label>
	                    <input class="form-control" name="fname" 
	                  id="irst_name_teacher"  placeholder="Prenom" type="text" />
	                    
	                </div>

	                <div class="form-group">
	                    <label for="name">Nom :</label>
	                    <input class="form-control" name="lname" 
	                     id="last_name_teacher" placeholder="Nom" type="text" />
	                    
	                </div>

	                <div class="form-group">
	                    <label for="name">Adresse :</label>
	                    <input class="form-control" name="adress" id="adress" placeholder="Adresse" type="text"/>
	                   
	                </div>

	                <div class="form-group">
	                    <label for="name">Ville :</label>
	                    <input class="form-control" name="city" id="city" placeholder="Ville" type="text"/>
	                    
	                </div>

	                <div class="form-group row col-xs-9">
	                 
						<label name="modules">Module:</label>
							
								
							<select name="modules[]" class="form-control select2-multi" multiple="multiple">
					@foreach($modules as $module)
					<option value="{{$module->id}}">{{$module->entitled_module}}</option>
					@endforeach
				</select>

					<a href="{{route('modules.create')}}" class="btn btn-primary">Créer</a>
							
				
				</div>

			
	                <div class="form-group">
		                <div class="row">
		                    <div class="col-md-12">
		                        <label for="name" class="control-label">Photo</label>
		                       
		                      </div>


		                </div>
		            </div>
  <div class="form-group">
		                <div class="row">
		                    <div class="col-md-12">
		                    	 <input type="file" name="image" id="image" class="form-control">
		                    </div>
		                </div>
		            </div>
	                
	                <div class="form-group">
	                    <label for="email">Email :</label>
	                    <input class="form-control" name="email" id="email" placeholder="Email" type="text"/>
	                    
	                </div>

	                <div class="form-group">
	                    <label for="name">Telephone :</label>
	                    <input class="form-control" name="phone" id="phone_number" placeholder="Telephone" type="text"/>
	                   
	                </div>

	                <div class="form-group">
	                    <input name="submit" type="submit" class="btn btn-primary" value="Inserer" />
	                    <input name="cancel" type="reset" class="btn btn-default" value="Cancel" />
	                </div>
	                
	            </div>
	        </div>
	  
</form>
</div>
</div>
@endsection
@section('script')
{!! Html::script('js/select2.min.js') !!}

<script type="text/javascript">
$('.select2-multi').select2();
</script>
@endsection

resources/views/Admin/teachers/edit.blade.php
@extends('main')

@section('stylesheet')

{!! Html::style('css/select2.min.css') !!}

@section('content')

 <div class="row">
      <div class="col-md-6 col-md-offset-3">
	        <div class="panel panel-default">
	            <div class="panel-heading">
	                <h4>Creation d'un compte enseignant</h4>
	            </div>
	            <div class="panel-body">
	           
	              <form action="{{route('teachers.update',$teacher->id)}}" method="POST">
		{{csrf_field()}}  
	    {{method_field('PUT')}}
	           

	              
					
					<div class="form-group">
	                    <label for="name">Prenom :</label>
	                    <input class="form-control" name="fname" 
	                  id="fname"  placeholder="Prenom" type="text" value="{{$teacher->fname}}" />
	                    
	                </div>

	                <div class="form-group">
	                    <label for="name">Nom :</label>
	                    <input class="form-control" name="lname" 
	                     id="lname" placeholder="Nom" type="text" value="{{$teacher->lname}}" />
	                    
	                </div>

	                <div class="form-group">
	                    <label for="name">Adresse :</label>
	                    <input class="form-control" name="adress" id="adress" placeholder="Adresse" type="text" value="{{$teacher->adress}}" />
	                   
	                </div>

	                <div class="form-group">
	                    <label for="name">Ville :</label>
	                    <input class="form-control" name="city" id="city" placeholder="Ville" type="text" value="{{$teacher->city}}" />
	                    
	                </div>

	                <div class="form-group row col-xs-9">
	                 
						<label name="modules">Module:</label>
							
								
							<select name="modules[]" class="form-control select2-multi" multiple="multiple">
					@foreach($modules as $module)
					<option value="{{$module->id}}">{{$module->entitled_module}}</option>
					@endforeach
				</select>

					<a href="{{route('modules.create')}}" class="btn btn-primary">Créer</a>
							
				
				</div>

			
	                <div class="form-group">
		                <div class="row">
		                    <div class="col-md-12">
		                        <label for="name" class="control-label">Photo</label>
		                       
		                      </div>


		                </div>
		            </div>
  					<div class="form-group">
		                <div class="row">
		                    <div class="col-md-12">
		                    	 <input type="file" name="image" id="image" class="form-control">
		                    </div>
		                </div>
		            </div>
	                
	                <div class="form-group">
	                    <label for="email">Email :</label>
	                    <input class="form-control" name="email" id="email" placeholder="Email" type="text" value="{{$teacher->email}}" />
	                    
	                </div>

	                <div class="form-group">
	                    <label for="name">Telephone :</label>
	                    <input class="form-control" name="phone" id="phone_number" placeholder="Telephone" type="text" value="{{$teacher->phone}}" />
	                   
	                </div>

	                <div class="form-group">
	                    <input name="submit" type="submit" class="btn btn-primary" value="Modifier" />
	                    <input name="cancel" type="reset" class="btn btn-default" value="Cancel" />
	                </div>
	                </form>
	            </div>
	        </div>
	  

</div>
</div>
@endsection

@section('script')
{!! Html::script('js/select2.min.js') !!}

<script type="text/javascript">
$('.select2-multi').select2();


</script>
@endsection

resources/views/Admin/teachers/show.blade.php
@extends('main')


@section('stylesheet')
{!! Html::style('css/custom.min.css') !!}

@section('content')


	<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-sm-6 col-md-4">
                        <img src="http://placehold.it/380x500" alt="" class="img-rounded img-responsive" />
                    </div>
                    <div class="col-sm-6 col-md-8">
                        <h4>
                            {{$teacher->fname}} {{$teacher->lname}}</h4>
                        <small><cite title="adresse"> {{$teacher->adress}}<i class="glyphicon glyphicon-map-marker">
                        </i></cite></small>
                        <p>
                            <i class="glyphicon glyphicon-envelope"></i>{{$teacher->email}}
                            <br />
                           
                            <br />
                            <i class="glyphicon glyphicon-gift"></i>{{$teacher->phone}}</p>
                       
                      
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h3>Liste des enseignants</h3>
     <div class="col-md-6 col-md-offset-3">
			<table class="table table-striped table-inverse">
		    	<thead>
		    		<tr>
		        		<th>Les modules</th>
		        		<th>Les classes</th>

		      		</tr>
		    	</thead>
		    	<tbody>
		    	<tr>
		    		<td>modules</td>
		    		<td>classes</td>
		    	</tr>
		    	</tbody>
		    	</table></div>
		    	</div>
</div>

@endsection